package org.komlev;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Created by Alex on 08.02.14.
 */
public class TaskProcessor {

    private Connection connection;
    private DataSource dataSource;

    public void setDataSource(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public void initScheme() {

        try {
            connection = dataSource.getConnection();

            PreparedStatement psCreate = connection.prepareStatement(
                    "CREATE TABLE RUNS(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL " +
                            "PRIMARY KEY, RUN_NAME VARCHAR(255) NOT NULL)");
            psCreate.execute();
            PreparedStatement psUpdate = connection.prepareStatement("INSERT INTO RUNS VALUES(1, 'RUN1')");
            psUpdate.execute();
            psUpdate.close();
            psCreate.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    public int execute() {
        int cnt = 0;

        if (connection == null) {
            try {
                connection = dataSource.getConnection();
            } catch (SQLException e) {
                return cnt;
            }
        }

        try {
            PreparedStatement statement = connection.prepareStatement("select * from RUNS");
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                System.out.println(rs.getString("RUN_NAME"));
                cnt++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return cnt;
    }
}
